INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (101, 'SNAP','300$','JHON', 'APPROVED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (102, 'SNAP','NA','SMITH', 'DENIED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (103, 'CCAP','250$','BUTLER', 'APPROVED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (104, 'CCAP','NA','ROOTS', 'DENIED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (105, 'QHP','480$','ORLEN', 'APPROVED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (106, 'QHP','NA','CHARLES', 'DENIED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (107, 'MEDICAID','300$','KATHY', 'APPROVED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (108, 'MEDICAID','NA','JAMES', 'DENIED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (109, 'MEDICARE','300$','STEVE', 'APPROVED');
INSERT INTO INSURANCE_PLANS (PLAN_ID, PLAN_NAME, BENEFIT_AMOUNT, HOLDER_NAME, PLAN_STATUS) VALUES (110, 'MEDICARE','NA','NIKA', 'TERMINATED');


